import jsPDF from 'jspdf';
import type { Consultation } from '../Types/index';

export const downloadPDFReport = async (consultation: Consultation) => {
  const doc = new jsPDF();
  
  const patientName = consultation.userId && typeof consultation.userId === 'object' 
    ? `${consultation.userId.firstName} ${consultation.userId.lastName}`
    : 'Unknown Patient';
    
  const doctorName = consultation.doctorId && typeof consultation.doctorId === 'object' 
    ? `Dr. ${consultation.doctorId.firstName} ${consultation.doctorId.lastName}`
    : 'Dr. Unknown';

  // Title
  doc.setFontSize(20);
  doc.text('CLINICFLOW MEDICAL REPORT', 20, 20);
  
  // Patient Info
  doc.setFontSize(12);
  doc.text(`Patient: ${patientName}`, 20, 40);
  doc.text(`Doctor: ${doctorName}`, 20, 50);
  doc.text(`Date: ${new Date(consultation.consultationDate).toLocaleDateString()}`, 20, 60);
  
  // Consultation Details
  doc.text('Consultation Details:', 20, 80);
  doc.setFontSize(10);
  doc.text(`Reason: ${consultation.consultationReason}`, 25, 90);
  doc.text(`Diagnosis: ${consultation.diagnosis}`, 25, 100);
  doc.text(`Notes: ${consultation.doctorNotes}`, 25, 110);
  
  // Vital Signs
  doc.setFontSize(12);
  doc.text('Vital Signs:', 20, 130);
  doc.setFontSize(10);
  doc.text(`Blood Type: ${consultation.bloodType}`, 25, 140);
  doc.text(`Weight: ${consultation.weight} kg`, 25, 150);
  doc.text(`Height: ${consultation.height} m`, 25, 160);
  doc.text(`Blood Pressure: ${consultation.bloodPressure}`, 25, 170);
  doc.text(`Temperature: ${consultation.temperature} °C`, 25, 180);
  doc.text(`Heart Rate: ${consultation.heartRate || consultation.hearRate} bpm`, 25, 190);
  
  // Footer
  doc.setFontSize(8);
  doc.text('Confidential Medical Document - Generated by ClinicFlow', 20, 280);
  doc.text(new Date().toLocaleString(), 20, 285);
  
  // Save the PDF
  const filename = `consultation-report-${new Date().getTime()}.pdf`;
  doc.save(filename);
};